"""Schéma initial

Révision : 0001
Précédente :
Créée le : 2026-09-28 03:05:47.765918
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import kobr4.db.models

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("ts", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_user_id"), ["user_id"], unique=False)

    op.create_table(
        "bot_events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("bot_id", sa.String(length=32), nullable=False),
        sa.Column("ts", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("type", sa.String(length=48), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bot_events", schema=None) as batch_op:
        batch_op.create_index("ix_bot_events_bot_ts", ["bot_id", "ts"], unique=False)

    op.create_table(
        "equity_points",
        sa.Column("bot_id", sa.String(length=32), nullable=False),
        sa.Column("ts", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("balance", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("equity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("bot_id", "ts"),
    )
    op.create_table(
        "trades",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("bot_id", sa.String(length=32), nullable=False),
        sa.Column("position_id", sa.String(length=80), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=7), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("opened_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("closed_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=16), nullable=False),
        sa.Column("pnl", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("commission", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("financing", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_id", "position_id"),
    )
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.create_index("ix_trades_bot_closed", ["bot_id", "closed_at"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("totp_secret", sa.Text(), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "recovery_codes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("onboarding_step", sa.String(length=32), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("locked_until", kobr4.db.models.UtcDateTime(timezone=True), nullable=True),
        sa.Column("created_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("backtest_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_backtest_runs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "broker_connections",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("broker", sa.String(length=32), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("token_encrypted", sa.Text(), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("account_currency", sa.String(length=3), nullable=True),
        sa.Column("verified_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=True),
        sa.Column("created_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("broker_connections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broker_connections_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "notification_settings",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("telegram_token_encrypted", sa.Text(), nullable=True),
        sa.Column("telegram_chat_id", sa.String(length=64), nullable=True),
        sa.Column("notify_trades", sa.Boolean(), nullable=False),
        sa.Column("notify_risk", sa.Boolean(), nullable=False),
        sa.Column("notify_daily_summary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("mfa_passed", sa.Boolean(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "bots",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("broker_connection_id", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("desired_state", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("live_confirmed_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=True),
        sa.Column("created_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_connection_id"], ["broker_connections.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bots_user_id"), ["user_id"], unique=False)

    op.create_table(
        "proposals",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("bot_id", sa.String(length=32), nullable=True),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", kobr4.db.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("proposals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_proposals_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proposals_user_id"))

    op.drop_table("proposals")
    with op.batch_alter_table("bots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bots_user_id"))

    op.drop_table("bots")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))

    op.drop_table("sessions")
    op.drop_table("notification_settings")
    with op.batch_alter_table("broker_connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broker_connections_user_id"))

    op.drop_table("broker_connections")
    with op.batch_alter_table("backtest_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backtest_runs_user_id"))

    op.drop_table("backtest_runs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index("ix_trades_bot_closed")

    op.drop_table("trades")
    op.drop_table("equity_points")
    with op.batch_alter_table("bot_events", schema=None) as batch_op:
        batch_op.drop_index("ix_bot_events_bot_ts")

    op.drop_table("bot_events")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_user_id"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
